### ISSUE TITLE
Unable to longpoll on cursor

### ISSUE THREAD

**Issue by Teteros** [Melinysh/dropboxfs#1]
After rsync -a to mirror dropboxfs mount, dropboxfs shortly panics:
```
2018/11/10 00:12:01 Requested lookup for dbox
2018/11/10 00:12:01 Directory  cached. Not fetching.
2018/11/10 00:12:01 Found match for directory lookup
2018/11/10 00:12:00 Starting polling call on cursor [IDs]
[...]
2018/11/10 00:12:06 Unable to longpoll on cursor [ID]
Post https://notify.dropboxapi.com/2/files/list_folder/longpoll: EOF
panic: Unable to longpoll on cursor [ID] Post https://notify.dropboxapi.com/2/files/list_folder/longpoll: EOF
goroutine 30682 [running]:
log.Panicln(0xc002b8def8, 0x3, 0x3)
        /usr/lib/go/src/log/log.go:340 +0xc0
github.com/melinysh/dropboxfs/fuse.(*Dropbox).beginBackgroundPolling.func1(0xc0001140c0, 0xc001bfcb60, 0x183)
        /tmp/gopath/src/github.com/melinysh/dropboxfs/fuse/dropbox.go:112 +0x559
created by github.com/melinysh/dropboxfs/fuse.(*Dropbox).beginBackgroundPolling
        /tmp/gopath/src/github.com/melinysh/dropboxfs/fuse/dropbox.go:95 +0xb1
```

**Comment by Melinysh** [comment]
Looking into the error, I found https://stackoverflow.com/questions/17714494/golang-http-request-results-in-eof-errors-when-making-multiple-requests-successi. It seems most likely we're hitting a rate limit. Which version of Go are you using?

**Comment by Teteros** [comment]
`go version`
go version go1.11.2 linux/amd64
